GET http://localhost:5050/api/auth/facebook

###

POST http://localhost:5050/api/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}

###

POST http://localhost:5050/api/auth/login
Content-Type: application/json

{
  "email": "chungnh@gmail.com",
  "password": "chungnh"
}

###

POST http://localhost:5050/api/auth/login
Content-Type: application/json

{
  "username": "longkt",
  "password": "longkt"
}

###

POST http://localhost:5050/api/auth/register
Content-Type: application/json

{
  "username": "longkt2",
  "email": "longkt2@gmail.com",
  "password": "longkt2"
}

###

POST http://localhost:5050/api/auth/register-by-admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNodW5nbmhAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTYzMzYyMTQ0MiwiZXhwIjoxNjMzNjIzMjQyfQ.I26K5TRl1xGevMitWCFyAiDtF4So-3Lm_saCCL6GZVc
Content-Type: application/json 

{
  "username": "longkt2",
  "email": "longkt2@gmail.com",
  "password": "longkt2",
  "is_admin": false
}

###

DELETE  http://localhost:5050/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjU4LCJpYXQiOjE2Mjg4MzEyOTcsImV4cCI6MTYyODgzMzA5N30.BeFEfATwGzDr9hCbBlnEwhyqIje3s9LroxbqPpDhgiM

###

POST  http://localhost:5050/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2MzI5MTMyNTAsImV4cCI6MTYzMjk5OTY1MH0.5tIO7I6yCwRJvlp-C9PA-pex4_ZWw4_9pebjmNUo_Pg"
}

###

GET http://localhost:5050/api/auth/me
Authorization: Bearer 

###

GET http://localhost:5050/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2MzM1Nzk3NTAsImV4cCI6MTYzMzU4MTU1MH0.9m87VnZw55xZcjF7SlZkhZdbwaqWzC2x6VcakyFxWvg



