
GET  http://localhost:5050/api/todo/detail/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvbmdrdDFAZ21haWwuY29tIiwiaWQiOjQsImlhdCI6MTYzMzQyNDA0NCwiZXhwIjoxNjMzNDI1ODQ0fQ.PdlhJisMOn041BPVQFPBulnN25Fnh7HygtdlJvN5xTM

###

GET http://localhost:5050/api/todo/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvbmdrdDFAZ21haWwuY29tIiwiaWQiOjQsImlhdCI6MTYzMzQyNDA0NCwiZXhwIjoxNjMzNDI1ODQ0fQ.PdlhJisMOn041BPVQFPBulnN25Fnh7HygtdlJvN5xTM

###

POST  http://localhost:5050/api/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvbmdrdDFAZ21haWwuY29tIiwiaWQiOjQsImlhdCI6MTYzMzQyNDA0NCwiZXhwIjoxNjMzNDI1ODQ0fQ.PdlhJisMOn041BPVQFPBulnN25Fnh7HygtdlJvN5xTM
Content-Type: application/json

{
  "name": "Coding Unilever",
  "content": "Finish before deadline of this midnight",
  "type": 1

}

###


PUT   http://localhost:5050/api/todo/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvbmdrdDFAZ21haWwuY29tIiwiaWQiOjQsImlhdCI6MTYzMzQyNDA0NCwiZXhwIjoxNjMzNDI1ODQ0fQ.PdlhJisMOn041BPVQFPBulnN25Fnh7HygtdlJvN5xTM
Content-Type: application/json

{
  "name": "Coding Unilever",
  "content": "Finish and meet deadline",
  "is_completed": true,
  "type": 1
}

###

DELETE   http://localhost:5050/api/todo/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvbmdrdDFAZ21haWwuY29tIiwiaWQiOjQsImlhdCI6MTYzMzQyNDA0NCwiZXhwIjoxNjMzNDI1ODQ0fQ.PdlhJisMOn041BPVQFPBulnN25Fnh7HygtdlJvN5xTM

###

GET  http://localhost:5050/api/todo/admin/detail/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2MzM0MjQ1MTYsImV4cCI6MTYzMzQyNjMxNn0.OZssiAGdy4L4ey4jcmlRlrTg3jNMiAcdOE13pcb_jvs

###

GET  http://localhost:5050/api/todo/admin/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2MzM0MjQ1MTYsImV4cCI6MTYzMzQyNjMxNn0.OZssiAGdy4L4ey4jcmlRlrTg3jNMiAcdOE13pcb_jvs
